apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        app: user-service
    spec:
      containers:
        - name: user-service
          image: shiroin/user-service:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: DB_HOST
              value: postgres-service
            - name: DB_NAME
              value: yourdb
            - name: DB_PASSWORD
              value: yourpassword
            - name: DB_USER
              value: youruser
            - name: DB_PORT
              value: "5432"
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8080
            initialDelaySeconds: 3
            periodSeconds: 10
        - name: debug-container
          image: busybox
          command: ["sh", "-c", "while true; do sleep 30; done;"]
