apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        app: user-service
    spec:
      containers:
        - name: user-service
          image: your-dockerhub-username/user-service:latest
          ports:
            - containerPort: 8080
          env:
            - name: POSTGRES_CONN
              value: "host=postgres-service port=5432 user=youruser password=yourpassword dbname=yourdb sslmode=disable"
---
apiVersion: v1
kind: Service
metadata:
  name: user-service
spec:
  selector:
    app: user-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
